<?php
if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_content-sections',
        'title' => 'Content Sections',
        'fields' => array (
            array (
                'key' => 'field_54b8546d8dfc2',
                'label' => 'Content Sections',
                'name' => 'content_sections',
                'type' => 'flexible_content',
                'layouts' => array (
                    array (
                        'label' => 'Main Content',
                        'name' => 'main_content',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54b8550922cb1',
                                'label' => 'Content',
                                'name' => 'content',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'General Content with Background Image',
                        'name' => 'general_content',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c29c35cb7ce',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54c29c35cb7cf',
                                'label' => 'Content',
                                'name' => 'content',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_54c29c35cb7d0',
                                'label' => 'Background Image',
                                'name' => 'background_image',
                                'type' => 'image',
                                'column_width' => '',
                                'save_format' => 'url',
                                'preview_size' => 'full',
                                'library' => 'all',
                            ),
                            array (
                                'key' => 'field_54c29c35cb7d1',
                                'label' => 'Font Color',
                                'name' => 'font_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '#000000',
                            ),
                            array (
                                'key' => 'field_550aed698c49e',
                                'label' => 'Dark Overlay',
                                'name' => 'darkened_overlay',
                                'type' => 'select',
                                'column_width' => '',
                                'choices' => array (
                                    'overlayon' => 'On',
                                    'overlayoff' => 'Off',
                                ),
                                'default_value' => '',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                    array (
                        'label' => 'General No Background Image',
                        'name' => 'general_no_bg_image',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54b8554c22cb4',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54b8555822cb5',
                                'label' => 'Content',
                                'name' => 'content',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_54b8556122cb6',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                            array (
                                'key' => 'field_54b85799fd469',
                                'label' => 'Font Color',
                                'name' => 'font_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '#000000',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Four Column Content',
                        'name' => 'four_column_content',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54de72187861a',
                                'label' => 'Section Title',
                                'name' => 'section_title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54de72187861b',
                                'label' => 'Section Intro',
                                'name' => 'section_intro',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_54de72187861c',
                                'label' => 'Columns',
                                'name' => 'columns',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_54de72187861d',
                                        'label' => 'Column',
                                        'name' => 'column',
                                        'type' => 'wysiwyg',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'toolbar' => 'full',
                                        'media_upload' => 'yes',
                                    ),
                                ),
                                'row_min' => 4,
                                'row_limit' => 4,
                                'layout' => 'table',
                                'button_label' => 'Add Column',
                            ),
                            array (
                                'key' => 'field_54de72187861e',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                            array (
                                'key' => 'field_54de72187861f',
                                'label' => 'Font Color',
                                'name' => 'font_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Three Column Content',
                        'name' => 'three_column_content',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c18675ca6f8',
                                'label' => 'Section Title',
                                'name' => 'section_title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54c18682ca6f9',
                                'label' => 'Section Intro',
                                'name' => 'section_intro',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_54b85acf418e1',
                                'label' => 'Columns',
                                'name' => 'columns',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_54b85ad9418e2',
                                        'label' => 'Column',
                                        'name' => 'column',
                                        'type' => 'wysiwyg',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'toolbar' => 'full',
                                        'media_upload' => 'yes',
                                    ),
                                ),
                                'row_min' => 3,
                                'row_limit' => 3,
                                'layout' => 'table',
                                'button_label' => 'Add Column',
                            ),
                            array (
                                'key' => 'field_54b85b943a1f1',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                            array (
                                'key' => 'field_54b85ba53a1f2',
                                'label' => 'Font Color',
                                'name' => 'font_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Two Column Content',
                        'name' => 'two_column_content',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c2a04d32c28',
                                'label' => 'Section Title',
                                'name' => 'section_title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54c2a04d32c29',
                                'label' => 'Section Intro',
                                'name' => 'section_intro',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_54c2a04d32c2a',
                                'label' => 'Columns',
                                'name' => 'columns',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_54c2a04d32c2b',
                                        'label' => 'Column',
                                        'name' => 'column',
                                        'type' => 'wysiwyg',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'toolbar' => 'full',
                                        'media_upload' => 'yes',
                                    ),
                                ),
                                'row_min' => 2,
                                'row_limit' => 2,
                                'layout' => 'table',
                                'button_label' => 'Add Column',
                            ),
                            array (
                                'key' => 'field_54c2a04d32c2c',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                            array (
                                'key' => 'field_54c2a04d32c2d',
                                'label' => 'Font Color',
                                'name' => 'font_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                        ),
                    ),
                    array (
                        'label' => '4 Photo Section',
                        'name' => '4_photo_section',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54d11f4dfaf61',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54d11f54faf62',
                                'label' => 'Intro',
                                'name' => 'intro',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_54c28f4bdc2a8',
                                'label' => 'Photo Row',
                                'name' => 'photo_row',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_54c28f5ddc2a9',
                                        'label' => 'Photos',
                                        'name' => 'photos',
                                        'type' => 'repeater',
                                        'column_width' => '',
                                        'sub_fields' => array (
                                            array (
                                                'key' => 'field_54c28f6cdc2aa',
                                                'label' => 'Photos',
                                                'name' => 'photos',
                                                'type' => 'image',
                                                'instructions' => 'Image Size: 460x400',
                                                'column_width' => '',
                                                'save_format' => 'id',
                                                'preview_size' => 'grid-sidebyside',
                                                'library' => 'all',
                                            ),
                                        ),
                                        'row_min' => 2,
                                        'row_limit' => 2,
                                        'layout' => 'table',
                                        'button_label' => 'Add Row',
                                    ),
                                ),
                                'row_min' => '',
                                'row_limit' => '',
                                'layout' => 'table',
                                'button_label' => 'Add Photo Row',
                            ),
                            array (
                                'key' => 'field_54c2a1c3c2d5e',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Video + Image Section',
                        'name' => 'video_image_section',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c2a26c530f7',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54c2a276530f8',
                                'label' => 'Intro',
                                'name' => 'intro',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_54c28fd4dc2b0',
                                'label' => 'Video Embed',
                                'name' => 'video_embed',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_54c28fe9dc2b1',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'column_width' => '',
                                'save_format' => 'id',
                                'preview_size' => 'grid-sidebyside',
                                'library' => 'all',
                            ),
                            array (
                                'key' => 'field_54c2a18cc2d5b',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                            array (
                                'key' => 'field_54c2a81b02cfc',
                                'label' => 'Font Color',
                                'name' => 'font_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Video + Image Section (Video Right)',
                        'name' => 'video_image_section_right',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c2a253530f5',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54c2a25f530f6',
                                'label' => 'Intro',
                                'name' => 'intro',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_54c2900ddc2b4',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'column_width' => '',
                                'save_format' => 'id',
                                'preview_size' => 'grid-sidebyside',
                                'library' => 'all',
                            ),
                            array (
                                'key' => 'field_54c2900ddc2b3',
                                'label' => 'Video Embed',
                                'name' => 'video_embed',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_54c2a19bc2d5c',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                            array (
                                'key' => 'field_54c2a6b102cfb',
                                'label' => 'Font Color',
                                'name' => 'font_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Recent Blog Posts Section',
                        'name' => 'blog_posts_section',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54c66227e9e44',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54c6622fe9e45',
                                'label' => 'Intro',
                                'name' => 'intro',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_54c662da4907b',
                                'label' => 'Articles Link',
                                'name' => 'articles_link',
                                'type' => 'page_link',
                                'instructions' => 'Add the link to where you have your blog',
                                'column_width' => '',
                                'post_type' => array (
                                    0 => 'page',
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Rotator',
                        'name' => 'general_rotator',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54cbc8e928c41',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54cbc8e928c42',
                                'label' => 'Intro',
                                'name' => 'intro',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_54cbc8e928c43',
                                'label' => 'Rotator Content ',
                                'name' => 'rotator_content',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_54cbc8e928c44',
                                        'label' => 'Content',
                                        'name' => 'content',
                                        'type' => 'wysiwyg',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'toolbar' => 'full',
                                        'media_upload' => 'yes',
                                    ),
                                ),
                                'row_min' => 1,
                                'row_limit' => '',
                                'layout' => 'table',
                                'button_label' => 'Add Slide',
                            ),
                            array (
                                'key' => 'field_54cbc8e928c45',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                            array (
                                'key' => 'field_54cbc8e928c46',
                                'label' => 'Font Color',
                                'name' => 'font_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Large Background Image Links',
                        'name' => 'large_background_images',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54d0fa21bfc35',
                                'label' => 'Large Image Section',
                                'name' => 'large_image_section',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_54d0fa3d801f5',
                                        'label' => 'Title',
                                        'name' => 'title',
                                        'type' => 'text',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'html',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_54d0fa9f801f6',
                                        'label' => 'Content',
                                        'name' => 'content',
                                        'type' => 'textarea',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => '',
                                        'formatting' => 'br',
                                    ),
                                    array (
                                        'key' => 'field_54d0fad3801f7',
                                        'label' => 'Background Image',
                                        'name' => 'background_image',
                                        'type' => 'image',
                                        'column_width' => '',
                                        'save_format' => 'url',
                                        'preview_size' => 'full',
                                        'library' => 'all',
                                    ),
                                    array (
                                        'key' => 'field_54d0fae7801f8',
                                        'label' => 'Link',
                                        'name' => 'link',
                                        'type' => 'page_link',
                                        'column_width' => '',
                                        'post_type' => array (
                                            0 => 'page',
                                        ),
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                    ),
                                ),
                                'row_min' => 1,
                                'row_limit' => 4,
                                'layout' => 'row',
                                'button_label' => 'Add Image',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Leadership Section',
                        'name' => 'leadership_section',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54dcda047b6b2',
                                'label' => 'Leadership Section',
                                'name' => 'leadership_section',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_54dcda147b6b3',
                                        'label' => 'Group Title',
                                        'name' => 'group_title',
                                        'type' => 'text',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'html',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_54dcda197b6b4',
                                        'label' => 'Leadership Group',
                                        'name' => 'leadership_group',
                                        'type' => 'repeater',
                                        'column_width' => '',
                                        'sub_fields' => array (
                                            array (
                                                'key' => 'field_54dcda307b6b5',
                                                'label' => 'Name',
                                                'name' => 'name',
                                                'type' => 'text',
                                                'column_width' => '',
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'formatting' => 'html',
                                                'maxlength' => '',
                                            ),
                                            array (
                                                'key' => 'field_54dcda367b6b6',
                                                'label' => 'Title',
                                                'name' => 'title',
                                                'type' => 'text',
                                                'column_width' => '',
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'formatting' => 'html',
                                                'maxlength' => '',
                                            ),
                                            array (
                                                'key' => 'field_54dcda3a7b6b7',
                                                'label' => 'Image',
                                                'name' => 'image',
                                                'type' => 'image',
                                                'instructions' => 'Image should be at least 200x200 square',
                                                'column_width' => '',
                                                'save_format' => 'url',
                                                'preview_size' => 'thumbnail',
                                                'library' => 'all',
                                            ),
                                            array (
                                                'key' => 'field_54dcda4e7b6b8',
                                                'label' => 'Connections',
                                                'name' => 'connections',
                                                'type' => 'repeater',
                                                'column_width' => '',
                                                'sub_fields' => array (
                                                    array (
                                                        'key' => 'field_54dcda5c7b6b9',
                                                        'label' => 'Link Name',
                                                        'name' => 'link_name',
                                                        'type' => 'select',
                                                        'column_width' => '',
                                                        'choices' => array (
                                                            'email' => 'Email',
                                                            'facebook' => 'Facebook',
                                                            'flickr' => 'Flickr',
                                                            'instagram' => 'Instagram',
                                                            'linkedin' => 'Linkedin',
                                                            'pinterest' => 'Pinterest',
                                                            'rss' => 'RSS',
                                                            'twitter' => 'Twitter',
                                                            'vimeo' => 'Vimeo',
                                                            'vine' => 'Vine',
                                                            'yelp' => 'Yelp',
                                                            'youtube' => 'Youtube',
                                                        ),
                                                        'default_value' => '',
                                                        'allow_null' => 0,
                                                        'multiple' => 0,
                                                    ),
                                                    array (
                                                        'key' => 'field_54dcda717b6ba',
                                                        'label' => 'Link',
                                                        'name' => 'link',
                                                        'type' => 'text',
                                                        'column_width' => '',
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                        'prepend' => '',
                                                        'append' => '',
                                                        'formatting' => 'html',
                                                        'maxlength' => '',
                                                    ),
                                                ),
                                                'row_min' => '',
                                                'row_limit' => '',
                                                'layout' => 'row',
                                                'button_label' => 'Add Connection',
                                            ),
                                        ),
                                        'row_min' => '',
                                        'row_limit' => '',
                                        'layout' => 'row',
                                        'button_label' => 'Add Leader',
                                    ),
                                ),
                                'row_min' => '',
                                'row_limit' => '',
                                'layout' => 'row',
                                'button_label' => 'Add Leadership Group',
                            ),
                        ),
                    ),
                ),
                'button_label' => 'Add Content Section',
                'min' => 0,
                'max' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-defaultnoheader.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'default',
                    'order_no' => 1,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'post_type',
                    'operator' => '!=',
                    'value' => 'post',
                    'order_no' => 2,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-donate.php',
                    'order_no' => 3,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-leadership.php',
                    'order_no' => 4,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-noheaderwsidebar.php',
                    'order_no' => 5,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'the_content',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_donate',
        'title' => 'Donate',
        'fields' => array (
            array (
                'key' => 'field_54caa2b97f580',
                'label' => 'Additional Donate Options',
                'name' => 'additional_donate_options',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_54caa2c17f581',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_54caa2c97f582',
                        'label' => 'Link',
                        'name' => 'link',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Donate Link',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-donate.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
                0 => 'permalink',
                1 => 'the_content',
                2 => 'excerpt',
                3 => 'custom_fields',
                4 => 'discussion',
                5 => 'comments',
                6 => 'revisions',
                7 => 'slug',
                8 => 'author',
                9 => 'format',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_home',
        'title' => 'Home',
        'fields' => array (
            array (
                'key' => 'field_550ada2bcf178',
                'label' => 'Home Banner Options',
                'name' => 'home_banner_options',
                'type' => 'flexible_content',
                'instructions' => 'Choose a banner style. Rotator or single image. ',
                'layouts' => array (
                    array (
                        'label' => 'Slider',
                        'name' => 'slider',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_550ada79cf17b',
                                'label' => 'Slider Images',
                                'name' => 'slider_images',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_550ada90cf17c',
                                        'label' => 'Image',
                                        'name' => 'image',
                                        'type' => 'image',
                                        'column_width' => '',
                                        'save_format' => 'url',
                                        'preview_size' => 'full',
                                        'library' => 'all',
                                    ),
                                    array (
                                        'key' => 'field_550b111e6f9eb',
                                        'label' => 'Slide Title',
                                        'name' => 'slide_title',
                                        'type' => 'text',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'html',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_550b112f6f9ec',
                                        'label' => 'Slide Content',
                                        'name' => 'slide_content',
                                        'type' => 'wysiwyg',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'toolbar' => 'full',
                                        'media_upload' => 'yes',
                                    ),
                                    array (
                                        'key' => 'field_550b1f66d6124',
                                        'label' => 'Darkened Overlay',
                                        'name' => 'darkened_overlay',
                                        'type' => 'select',
                                        'column_width' => '',
                                        'choices' => array (
                                            'overlayoff' => 'Off',
                                            'overlayon' => 'On',
                                        ),
                                        'default_value' => '',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                    ),
                                ),
                                'row_min' => '',
                                'row_limit' => '',
                                'layout' => 'row',
                                'button_label' => 'Add Slide',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Single Image',
                        'name' => 'single_image',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_550adab7cf17e',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'column_width' => '',
                                'save_format' => 'url',
                                'preview_size' => 'full',
                                'library' => 'all',
                            ),
                            array (
                                'key' => 'field_550adac3cf17f',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_550ae31401b41',
                                'label' => 'Content',
                                'name' => 'content',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_550ae3408fa2e',
                                'label' => 'Font Color',
                                'name' => 'font_color',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => '',
                            ),
                            array (
                                'key' => 'field_550ae34e8fa2f',
                                'label' => 'Darkened Overlay',
                                'name' => 'darkened_overlay',
                                'type' => 'select',
                                'column_width' => '',
                                'choices' => array (
                                    'overlayoff' => 'Off',
                                    'overlayon' => 'On',
                                ),
                                'default_value' => '',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                ),
                'button_label' => 'Add Row',
                'min' => 1,
                'max' => 1,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'home-page.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_leadership',
        'title' => 'Leadership',
        'fields' => array (
            array (
                'key' => 'field_54dbb181d6ddd',
                'label' => 'Secondary Leadership Section',
                'name' => 'secondary_leadership_section',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_54dbb181d6dde',
                        'label' => 'Group Title',
                        'name' => 'group_title',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_54dbb181d6ddf',
                        'label' => 'Leadership Group',
                        'name' => 'leadership_group',
                        'type' => 'repeater',
                        'column_width' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54dbb181d6de0',
                                'label' => 'Name',
                                'name' => 'name',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54dbb181d6de1',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'instructions' => 'Images should be square at least 200x200',
                                'column_width' => '',
                                'save_format' => 'url',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                            ),
                            array (
                                'key' => 'field_54dbb181d6de2',
                                'label' => 'Position',
                                'name' => 'position',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54dbb181d6de3',
                                'label' => 'Connections',
                                'name' => 'connections',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_54dbb181d6de4',
                                        'label' => 'Link Name',
                                        'name' => 'link_name',
                                        'type' => 'select',
                                        'column_width' => '',
                                        'choices' => array (
                                            'email' => 'email',
                                            'facebook' => 'facebook',
                                            'flickr' => 'flickr',
                                            'instagram' => 'instagram',
                                            'linkedin' => 'linkedin',
                                            'pinterest' => 'pinterest',
                                            'rss' => 'rss',
                                            'twitter' => 'twitter',
                                            'vimeo' => 'vimeo',
                                            'vine' => 'vine',
                                            'yelp' => 'yelp',
                                            'youtube' => 'youtube',
                                        ),
                                        'default_value' => '',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                    ),
                                    array (
                                        'key' => 'field_54dbb181d6de5',
                                        'label' => 'Link',
                                        'name' => 'link',
                                        'type' => 'text',
                                        'instructions' => 'for email links use mailto:name@domain.com',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'html',
                                        'maxlength' => '',
                                    ),
                                ),
                                'row_min' => '',
                                'row_limit' => '',
                                'layout' => 'table',
                                'button_label' => 'Add Link',
                            ),
                        ),
                        'row_min' => '',
                        'row_limit' => '',
                        'layout' => 'row',
                        'button_label' => 'Add Leader',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Add Leadership Group',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-leadership.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'permalink',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'slug',
                7 => 'author',
                8 => 'format',
                9 => 'featured_image',
                10 => 'categories',
                11 => 'tags',
                12 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_options',
        'title' => 'Options',
        'fields' => array (
            array (
                'key' => 'field_54c2c059dd55f',
                'label' => 'Mobile Menu Button Color',
                'name' => 'mobile_menu_link_font_color',
                'type' => 'color_picker',
                'default_value' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_pages',
        'title' => 'Pages',
        'fields' => array (
            array (
                'key' => 'field_550b23d7e14ab',
                'label' => 'Page Header Overlay',
                'name' => 'darkened_overlay',
                'type' => 'select',
                'choices' => array (
                    'overlayoff' => 'Off',
                    'overlayon' => 'On',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-defaultnoheader.php',
                    'order_no' => 1,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-noheader.php',
                    'order_no' => 2,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'home-page.php',
                    'order_no' => 3,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-fullwidth-nohead.php',
                    'order_no' => 4,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-donate.php',
                    'order_no' => 5,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'page_template',
                    'operator' => '!=',
                    'value' => 'page-noheaderwsidebar.php',
                    'order_no' => 6,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
}

?>